# 命令别名
alias ls='ls --color=auto'
alias ll='ls -al'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias tailf='tail -f -n'

# 环境变量
export PS1="\u@\[\e[1;93m\]\h\[\e[m\]:\w\\$\[\e[m\] "
export SIGNER_PUBLIC_KEY_HASHS=$(cat ${NODE_DATA_PATH}/node/octez-signer/public_key_hashs | jq -r .[0].value)
